/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckFile: typeof import('./src/components/CheckFile.vue')['default']
    EditName: typeof import('./src/components/EditPanels/EditName.vue')['default']
    EditSong: typeof import('./src/components/EditPanels/EditSong.vue')['default']
    EditVideo: typeof import('./src/components/EditPanels/EditVideo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Header: typeof import('./src/components/Header.vue')['default']
    Manual: typeof import('./src/components/Manual.vue')['default']
    MarkingCard: typeof import('./src/components/MarkingCard.vue')['default']
    MarkingTags: typeof import('./src/components/MarkingTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspendPanel: typeof import('./src/components/SuspendPanel.vue')['default']
    UpdateRanking: typeof import('./src/components/UpdateRanking.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile.vue')['default']
  }
}
